### ISSUE TITLE
BGP Neighbor and NAT-T issues with Nuage 5.1.1 release

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspk-python#15]
Since 5.1.1 has a changed default state for NAT-T for NSG network ports (enabled by default) creation of BGP Neighbor object fails with the following `warning` from VSD:

**Initial POST**
```
POST https://10.167.45.50:8443/nuage/api/v5_0/vlans/e2722e22-e074-4093-a7a8-49392a84f819/bgpneighbors 
headers: {'X-Nuage-Organization': 'BT_ORG_new', 'Content-Type': 'application/json', 'Authorization': 'XREST YWRtaW46NGYxNzE0NzAtYWQ0YS00NmNhLWJhM2MtNmM2YzY3OWM1MTA3'}
data:
  {
    "session": null, 
    "peerIP": "22.22.21.22", 
    "name": "PE_BGP_Neighbor", 
    "associatedExportRoutingPolicyID": null, 
    "peerAS": 65101, 
    "entityScope": null, 
    "parentType": null, 
    "associatedImportRoutingPolicyID": null, 
    "externalID": null, 
    "lastUpdatedDate": null, 
    "parentID": null, 
    "owner": null, 
    "dampeningEnabled": null, 
    "creationDate": null, 
    "ID": null, 
    "description": null
}
```
**received reply**:
```
< data:
{
    "errors": [
        {
            "property": "", 
            "descriptions": [
                {
                    "description": "BGP peering is not supported when NAT-T is enabled", 
                    "title": "BGP Neighbor validation error"
                }
            ]
        }
    ], 
    "internalErrorCode": 4606
}
```

**Question # 1:** why is it classified as a WARN and not ERROR?

**Question/Problem # 2:** It seems reasonable that if an object can not be created, it should not be returned  in any way. Yet I see misleading data when in my code for receiving an object after its creation:
```
child_obj = parent_obj.create_child(child_obj)[0]
```

I receive a corrupted object that has the following parameters reported back:
```
{'ID': None,
 'associatedExportRoutingPolicyID': None,
 'associatedImportRoutingPolicyID': None,
 'creationDate': None,
 'dampeningEnabled': None,
 'description': None,
 'entityScope': None,
 'externalID': None,
 'lastUpdatedDate': None,
 'name': u'PE_BGP_Neighbor',
 'owner': None,
 'parentID': None,
 'parentType': None,
 'peerAS': 65101,
 'peerIP': u'22.22.21.22',
 'session': None}
```
Note, that all the parameters are `None` but the ones that I tried to configure with initial POST.

**Comment by pdellaert** [comment]
@hellt , where do you see this as warning, i see that it is an error?

On Q2, The code you use below, is not a standard way:
`child_obj = parent_obj.create_child(child_obj)[0]`

The typical use should be:
`parent_obj.create_child(child_obj)`

That way will automatically update the child_obj. 

`create_child` will do an API call to try and create the child object. It executes the POST HTTP call with the json of the object, and if it succeeds, the API will return the full JSON representation of the object as it has been created in VSD. `create_child` will take that JSON and update the child_obj in place. 

If the HTTP call fails, it of course does not update the child_obj. 

At the end, it will return a list: `(child_obj, connection)`, but that child_obj will be either the updated object, if the POST succeeded, otherwise it returns exactly the object you gave. `connection` is the request (python module we use for HTTP requests) connection object that can be used to further analyse what has happened in case of a failure. (it contains information on the HTTP code returned, the response content, headers, ...)

In any case, you do not have to do `child_obj = parent_obj.create_child(child_obj)[0]`, you can just do `parent_obj.create_child(child_obj)`, it updates the object in case there is something to update.

This design seems to be in line with other API SDKs i've seen.

If you do want to save the return values of the `create_child`, because you want to analyse the connection, i'd always suggest to do:
`child_obj, connection = parent_obj.create_child(child_obj)`

**Comment by hellt** [comment]
Thanks @pdellaert for a perfect explanation. You made me to look once again at the code and it had all to do with a glitch in my legacy function.
